Jungle-High-Fish/EPIC-Cardinals

Assets/Modules/Core/Constants.cs
Assets/Modules/Entity/BaseEntity.cs
Assets/Modules/Entity/BuffPrefab.prefab.meta
Assets/Modules/Entity/Enemy/BaseEnemy.cs
Assets/Modules/Entity/Enemy/Enemies/Boss.cs
Assets/Modules/Entity/Enemy/Enemies/One.cs
Assets/Modules/Entity/Enemy/EnemyFactory.cs
Assets/Modules/Entity/Enemy/Pattern.cs
Assets/Modules/Entity/Enemy/UIEnemy.prefab.meta
Assets/Modules/Entity/Enemy/UIEnemyInfo.cs
Assets/Modules/Entity/Enemy/UIEnemyInfo.prefab
Assets/Modules/Entity/TempPlayer.cs
Assets/Modules/GameManager.cs
Assets/Scenes/MJTest.unity

몬스터 패턴이 UI에 알맞게 표시되도록 구현
적 전투 구현 및 관련 코드 수
적 패턴 설정 후, 패턴 타입에 따라 사전 행동 할 수 있도록 설정

[Feat] 몬스터 로직 추가

---

Assets/Modules/Card/Card.cs
Assets/Modules/Card/CardManager.cs
Assets/Modules/Card/CardUI.cs
Assets/Modules/Card/UICardUseSlot.cs
Assets/Modules/Core/Enums.cs

[Chore] 카드 관련 enum 정리했다굴~

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/Card/CardUI.cs
Assets/Modules/Core/Enums.cs
Assets/Resources/Prefabs/UI/Card/CardUI.prefab
Assets/Scenes/PotionTest.unity
ProjectSettings/Packages/com.unity.probuilder/Settings.json

[Feat] 휘발성 카드 생성 기능 구현했다굴~

---

Assets/Modules/Core/Enums.cs
Assets/Modules/Player/Player.cs
Assets/Modules/Player/PlayerInfo.cs
Assets/Modules/Player/Potion/FourPotion.cs
Assets/Modules/Player/Potion/FourPotion.cs.meta
Assets/Modules/Player/Potion/GrowthPotion.cs
Assets/Modules/Player/Potion/GrowthPotion.cs.meta
Assets/Modules/Player/Potion/HealPotion.cs
Assets/Modules/Player/Potion/JumpPotion.cs
Assets/Modules/Player/Potion/OnePotion.cs
Assets/Modules/Player/Potion/OnePotion.cs.meta
Assets/Modules/Player/Potion/Potion.cs
Assets/Modules/Player/Potion/QuickPotion.cs
Assets/Modules/Player/Potion/ReversePotion.cs
Assets/Modules/Player/Potion/ThreePotion.cs
Assets/Modules/Player/Potion/ThreePotion.cs.meta
Assets/Modules/Player/Potion/TwoPotion.cs
Assets/Modules/Player/Potion/TwoPotion.cs.meta
Assets/Modules/Stage/Board/Tile/TileMagic/TileMagic.cs
Assets/Resources/SO/Potions/Four.asset
Assets/Resources/SO/Potions/Four.asset.meta
Assets/Resources/SO/Potions/Growth.asset
Assets/Resources/SO/Potions/Growth.asset.meta
Assets/Resources/SO/Potions/One.asset
Assets/Resources/SO/Potions/One.asset.meta
Assets/Resources/SO/Potions/Three.asset
Assets/Resources/SO/Potions/Three.asset.meta
Assets/Resources/SO/Potions/Two.asset
Assets/Resources/SO/Potions/Two.asset.meta
Assets/Scenes/PotionTest.unity

[Feat] 포션 추가 구현

---

Assets/Modules/Stage/Board/Tile/Tile.cs

[Feat] 타일 도착 시 가능한 경우에 레벨업 하도록 변경

[Feat] 카드 선택 시 마우스 호버링 표시

---

Assets/Modules/Enemy/BaseEnemy.cs
Assets/Modules/Enemy/Enemies/Three1.cs
Assets/Modules/Enemy/Enemies/Three2.cs
Assets/Modules/Enemy/UI/UIEnemyInfo.cs
Assets/Modules/Entity/BaseEntity.cs
Assets/Modules/MainUI/UIEndTurnButton.cs
Assets/Modules/Player/Player.cs
Assets/Modules/Stage/Event/BattleEvent.cs

- [턴 종료] 버튼 선택 시, 플로우 순서대로 수행하지 않는 이슈 수정
- 보상 없는 몬스터의 예외처리 추가
- 데미지 계산식 수정
- 몬스터 관련 오류 수정

[Fix] 오류 수정

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/Player/Potion/DerivedPotions/GrowthPotion.cs

[Fix] 모서리 타일에서 행동 안되도록 수정 및 성장 포션 버그 수정했다굴

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/Player/Player.cs

[Fix] 워프 부적으로 이동했을 시 행동이 안되는 버그 수정했다굴~

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/Stage/Board/Event/Card/UICardEvent.cs
Assets/Resources/Prefabs/UI/Card/CardUI.prefab

[FIx] 일회성 카드 복사 이벤트 버그 수정했다굴~

---

Assets/Modules/Stage/Event/BattleEvent.cs

[Fix] 카드 행동 매번 초기화되던 버그 수정했다굴~

---

Assets/Modules/Player/Player.cs
Assets/Modules/Stage/Event/BattleEvent.cs
Assets/Plugins/Febucci.meta
Assets/Plugins/Febucci/Text Animator.meta
Assets/Plugins/Febucci/Text Animator/Extra.meta
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta

[Fix] 깨지지 않는 바위 축복 몬스터 잡으면 방어력 초기화 되도록 수정했다굴~

---

Assets/Modules/Card/UI/CardUI.cs
Assets/Resources/Prefabs/UI/Card/CardUI.prefab

[Feat] 카드 책갈피 연출 만들었다굴~

---

Assets/Modules/Card/UI/CardAnimation.cs
Assets/Scenes/Board/FlipTest.unity

[Fix] 턴 종료 후 카드 사라지는 애니메이션 수정

---

Assets/Modules/Card/CardManager.cs

[Fix] 카드 드로우 이벤트 관련 버그 수정

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/MainUI/Description/DescriptionConnector.cs
Assets/Modules/Stage/Board/Event/Card/UICardEvent.cs
Assets/Modules/Stage/Board/Event/Shop/UIProduct.cs
Assets/Modules/Stage/Board/Event/Tile/UITileEvent.cs
Assets/Modules/Stage/Board/Tile/TileAction/TileEventAction.cs
Assets/Resources/Prefabs/UI/BoardEvent/UIProduct.prefab

수정한 오류
- 상정 설명창 안뜨는 이슈
- 연속된 카드가 아닐때, 플레이어 말풍선 액션으로 표시
- 보드 이벤트들 오류 수정

[Feat] 보드 이펙트 추가 및 오류 수정 

---

Assets/Modules/Card/CardManager.cs
Assets/Modules/MainUI/Description/UIPotion.cs
Assets/Modules/Player/Potion/DerivedPotions/FourPotion.cs
Assets/Modules/Player/Potion/DerivedPotions/JumpPotion.cs
Assets/Modules/Player/Potion/DerivedPotions/OnePotion.cs
Assets/Modules/Player/Potion/DerivedPotions/ReversePotion.cs
Assets/Modules/Player/Potion/DerivedPotions/ThreePotion.cs
Assets/Modules/Player/Potion/DerivedPotions/TwoPotion.cs
Assets/Modules/Stage/StageController.cs

[Fix] 포션 관련 버그 수정했다굴

---

Assets/Modules/Player/Artifact/DerivedArtifacts/GrimoireSatchel.cs
Assets/Modules/Stage/StageController.cs

[Fix] 그리모어 가방 HP 바로 업데이트 안되는 버그 수정했다굴~

---

Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Resources/Prefabs/Enemy/EnemyAnimation/PazizizicBerserkRenderer.prefab

[Fix] 파지지직이 광폭화 애니메이션 재생 안되는 버그 수정

---

Assets/Modules/Entity/BaseEntity.cs
Assets/Modules/Player/Artifact/Artifact.cs
Assets/Modules/Player/Artifact/DerivedArtifacts/GrimoireSatchel.cs
Assets/Modules/Player/PlayerInfo.cs
Assets/Modules/Stage/StageController.cs
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
Assets/ThirdParty/Feel/FeelDemos/FeelTemplatesDemo.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v1.7/NiceVibrations-v-1-7.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v3.9/NiceVibrations-v-3-9-0.unitypackage.meta
Assets/ThirdParty/FlatKit/[Render Pipeline] Built-In.unitypackage.meta
Assets/ThirdParty/FlatKit/[Render Pipeline] Universal (URP).unitypackage.meta

[Fix] 상점에서 유물 사면 최대 체력 깎이는 버그 수정했다굴

---

Assets/Modules/Dice/DiceManager.cs
Assets/Modules/Player/Player.cs
Assets/Modules/Player/Potion/DerivedPotions/QuickPotion.cs

[Feat] 혼란 디버프 구현했다굴~

---

Assets/Modules/Dice/DiceDescription.cs
Assets/Modules/Dice/DiceUI.cs
Assets/Resources/Prefabs/UI/Dice/DiceSurface.prefab
Assets/Resources/Prefabs/UI/Dice/DiceUI.prefab

[Feat] 주사위 Description 리소스도 교체했다굴~

---

Assets/Modules/Dice/DiceManager.cs
Assets/Modules/Dice/DiceUI.cs
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta

[Feat] DiceManager에 ChangeDice() 함수 추가했다굴~

---

Assets/Modules/Core/Constants.cs
Assets/Modules/Core/UIManager.cs
Assets/Modules/Dice/Dice.cs
Assets/Modules/Dice/DiceManager.cs
Assets/Modules/MainUI/NewDice.meta
Assets/Modules/MainUI/NewDice/SelectedDice.cs
Assets/Modules/MainUI/NewDice/SelectedDice.cs.meta
Assets/Modules/MainUI/NewDice/SelectedEffect.cs
Assets/Modules/MainUI/NewDice/SelectedEffect.cs.meta
Assets/Modules/MainUI/NewDice/UIDice.cs
Assets/Modules/MainUI/NewDice/UIDice.cs.meta
Assets/Modules/MainUI/NewDice/UINewDicePanel.cs
Assets/Modules/MainUI/NewDice/UINewDicePanel.cs.meta
Assets/Modules/Stage/Board/Event/Roulette/UI/UIRoulette.cs
Assets/Modules/Stage/Reward/RewardBox.cs
Assets/Modules/Stage/Reward/UIRewardItem.cs
Assets/Modules/Stage/StageController.cs
Assets/Resources/Prefabs/UI/NewDicePanel.meta
Assets/Resources/Prefabs/UI/NewDicePanel/NewDicePanel.prefab
Assets/Resources/Prefabs/UI/NewDicePanel/NewDicePanel.prefab.meta
Assets/Resources/Prefabs/UI/NewDicePanel/UICurrentDice.prefab
Assets/Resources/Prefabs/UI/NewDicePanel/UICurrentDice.prefab.meta
Assets/Resources/Prefabs/UI/NewDicePanel/UINewDice.prefab
Assets/Resources/Prefabs/UI/NewDicePanel/UINewDice.prefab.meta

[Feat] 주사위 보상 패널 구현 완료 

---

Assets/Modules/Dice/DiceManager.cs
Assets/Modules/Dice/DiceUI.cs
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
Assets/Resources/AnimatorController/EarthDiceAnimator.controller
Assets/Resources/AnimatorController/EarthRoll.anim
Assets/Resources/AnimatorController/FireDiceAnimator.controller
Assets/Resources/AnimatorController/FireRoll.anim
Assets/Resources/AnimatorController/NormalDiceAnimator.controller
Assets/Resources/AnimatorController/NormalRoll.anim
Assets/Resources/AnimatorController/WaterDiceAnimator.controller
Assets/Resources/AnimatorController/WaterRoll.anim
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
Assets/ThirdParty/Feel/FeelDemos/FeelTemplatesDemo.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v1.7/NiceVibrations-v-1-7.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v3.9/NiceVibrations-v-3-9-0.unitypackage.meta

[Fix] 리롤 버그 수정했다굴~

---

Assets/Modules/Dice/DiceManager.cs
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
Assets/ThirdParty/Feel/FeelDemos/FeelTemplatesDemo.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v1.7/NiceVibrations-v-1-7.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v3.9/NiceVibrations-v-3-9-0.unitypackage.meta

굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~

[Fix] 슬로우 디버프 기능 수정했다굴~~~

---

Assets/Scenes/Main/Title.unity

[Fix] DiceTitleUI 만들어서 커밋한다굴~

---

Assets/Modules/Dice/DiceDescription.cs
Assets/Resources/Prefabs/UI/Dice/DiceUI.prefab

[Fix] 주사위 설명 길이 조절 했다굴~

---

Assets/Modules/Dice/DiceManager.cs
Assets/Modules/Player/Player.cs
Assets/Modules/Player/PlayerInfo.cs
Assets/Modules/Player/Potion/DerivedPotions/JumpPotion.cs
Assets/Modules/Player/Potion/DerivedPotions/ReversePotion.cs
Assets/Plugins/CW/Destructible2D/URP 2020.unitypackage.meta
Assets/Plugins/CW/Destructible2D/URP 2021.2.unitypackage.meta

- 플레이어 턴 아닐때 포션 사용 불가하게 수정
- 이동중일땐 이동 관련 포션 사용 안되게 수정
- 포션으로 이동할 때 주사위 사용 안되도록 수정 했다굴~
- 굴 굴 굴 굴굴 굴 굴 굴굴 굴굴

[Fix] 포션 관련 버그 수정했다굴~

---

Assets/Modules/Dice/DiceManager.cs

굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~굴~

[Fix] 슬로우 디버프 수정 및 포션도 슬로우 디버프 적용했다굴~

---

Assets/Modules/Dice/DiceUI.cs
Assets/Plugins/CW/Destructible2D/URP 2020.unitypackage.meta
Assets/Plugins/CW/Destructible2D/URP 2021.2.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
Assets/ThirdParty/Feel/FeelDemos/FeelTemplatesDemo.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v1.7/NiceVibrations-v-1-7.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v3.9/NiceVibrations-v-3-9-0.unitypackage.meta

[Chore] 주사위 효과음 위치 표시했다굴~

---

Assets/Modules/Enemy/BaseEnemy.cs
Assets/Modules/Enemy/Enemies/Pazizizizic.cs

- 광폭화 반복되는 이슈
- 파지직이 50% 미만 -> 이하로 조건 수정

[Fix] 광폭화 오류 수정 

---

Assets/Modules/Enemy/BaseEnemy.cs
Assets/Modules/Enemy/UIEnemyStatus.cs
Assets/Modules/Entity/BaseEntity.cs

[Fix] 무력 디버프 적용시 UI 최신화 안되는 버그 수정 및 디버프 적용 시 텍스트 색 변경했다굴~

---

Assets/Modules/Player/Player.cs
Assets/Modules/Stage/Board/Tile/UI/UITileExp.cs

- 타일 레벨 표현 버그 수정
- 최대 체력 저장 안되는 버그 수정

[Feat] 버그 일부 수정

---

Assets/Modules/MainUI/NewDice/UINewDicePanel.cs

보상받을때 패널 나갔다가 다시 들어오면 새로고침 안되는 버그 수정~
굴~

[Fix] 주사위 보상 새로고침 관련 버그 수정했다굴~

---

Assets/Modules/Stage/Reward/UIRewardItem.cs
Assets/Plugins/CW/Destructible2D/URP 2020.unitypackage.meta
Assets/Plugins/CW/Destructible2D/URP 2021.2.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
Assets/Resources/SO/Stage/Stage.asset
Assets/Scenes/Main/Title.unity
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
Assets/ThirdParty/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
Assets/ThirdParty/Feel/FeelDemos/FeelTemplatesDemo.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v1.7/NiceVibrations-v-1-7.unitypackage.meta
Assets/ThirdParty/Feel/NiceVibrations/OlderVersions/v3.9/NiceVibrations-v-3-9-0.unitypackage.meta

[Fix] 구름 가끔 선 생기는 버그 최대한 수정 및 마지막 보상 멘트 수정했다굴

---

Assets/Scenes/Main/Title.unity

[Fix] 구름이 통째로 사라지는 버그 수정했다굴..

---

Assets/Modules/Core/GameManager.cs
Assets/Modules/MainUI/NewDice/UINewDicePanel.cs
Assets/Modules/Stage/Event/BattleEvent.cs

[Fix] NEW DICE에서 새로고침 하고나서 패널 닫고 다시 열면 처음에 나왔던 주사위 나오는 버그 수정했다굴~
